pipeline {
    agent any

    tools {
        go 'Go 1.26.1' // use same define in contol setting
    }

    stages {
        state ("Unit Test"){
            parallel {
                    stage('Unit Test - Backend') {

                        steps {
                            dir ('bugtracker-backend'){
                                // Ensure the go-junit-report tool is available.
                                sh 'go install github.com/jstemmer/go-junit-report/v2@latest'
                                sh "export PATH=\$PATH:\$(go env GOPATH)/bin && go test -v ./... | go-junit-report > test-report.xml"
                                //Geneate coverage report
                                sh 'go test -coverprofile=coverage.out -covermode=atomic ./...'
                                sh 'go tool cover -html=coverage.out -o coverage.html'
                                sh '''
                                    mkdir -p bugtracker-backend/reports
                                    mv coverage.html bugtracker-backend/reports/
                                    ls -R bugtracker-backend/reports
                                '''
                            }
                        }
                        post {
                            always {
                                junit 'bugtracker-backend/test-report.xml'
                                publishHTML target:[
                                    reportDir: 'bugtracker-backend/reports',
                                    reportFiles: 'coverage.html',
                                    reportName: 'Backend Coverege Report'
                                ]
                            }
                        }
                    }
                    stage ('Unit Test - FrontEnd') {
                        agent {
                            docker {
                                image 'node:20-alpine'
                                reuseNode true
                            }
                        }
                        steps {
                            dir ('bugtracker-fronend'){
                                sh 'npm -v'
                            }

                        }
                    }
            }
        }
        // stage('Unit Test - Backend') {

        //     steps {
        //         dir ('bugtracker-backend'){
        //             // Ensure the go-junit-report tool is available.
        //              sh 'go install github.com/jstemmer/go-junit-report/v2@latest'
        //             sh "export PATH=\$PATH:\$(go env GOPATH)/bin && go test -v ./... | go-junit-report > test-report.xml"
        //             //Geneate coverage report
        //             sh 'go test -coverprofile=coverage.out -covermode=atomic ./...'
        //             sh 'go tool cover -html=coverage.out -o coverage.html'
        //             sh '''
        //                 mkdir -p bugtracker-backend/reports
        //                 mv coverage.html bugtracker-backend/reports/
        //                 ls -R bugtracker-backend/reports
        //             '''
        //         }
        //     }
        //     post {
        //         always {
        //             junit 'bugtracker-backend/test-report.xml'
        //             publishHTML target:[
        //                 reportDir: 'bugtracker-backend/reports',
        //                 reportFiles: 'coverage.html',
        //                 reportName: 'Backend Coverege Report'
        //             ]
        //         }
        //     }
        // }
        // stage ('Unit Test - FrontEnd') {
        //     agent {
        //         docker {
        //             image 'node:20-alpine'
        //             reuseNode true
        //         }
        //     }
        //     steps {
        //         dir ('bugtracker-fronend'){
        //             sh 'npm -v'
        //         }

        //     }
        // }
    }
}